name: barcode-extractor

services:
  - name: web
    source_dir: /
    github:
      branch: main
    run_command: gunicorn server.index:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 120
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000

    envs:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: 'false'
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: '8000'
      - key: WORKERS
        value: '2'
      - key: MAX_FILE_SIZE
        value: '10485760'
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: ALLOWED_ORIGINS
        value: https://barcode-extractor.ondigitalocean.app

    build_command: |-
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-por poppler-utils libmagic1
      pip install -r server/requirements.txt

    routes:
      - path: /
